export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="prose max-w-none">
        <h1>Terms of Service</h1>
        <p>
          <em>Last Updated: December 25, 2024</em>
        </p>
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using RateMyProfessor.space (the "Service"), you agree to be bound by these Terms of
          Service ("Terms"). If you disagree with any part of the terms, you may not access the Service.
        </p>
        <h2>2. Use of Service</h2>
        <p>You agree to the following conditions of use:</p>
        <ul>
          <li>
            <strong>Age Requirement:</strong> You must be at least 13 years old or the minimum age of digital consent
            in your country to use our Service.
          </li>
          <li>
            <strong>Responsible Use:</strong> You agree not to misuse the Service or help anyone else to do so. This includes generating content that is knowingly false, malicious, defamatory, or in violation of any laws.
          </li>
        </ul>
        <h2>3. Intellectual Property and Content</h2>
        <p>
          The reviews generated by our AI are for your personal use as a starting point. You are solely responsible
          for the final content you create and post on any platform. We do not claim ownership of the content you
          generate.
        </p>
        <h2>4. Disclaimer of Warranty</h2>
        <p>
          The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We make no warranty that the Service will
          be uninterrupted, timely, secure, or error-free, or that the generated content will be accurate or
          reliable.
        </p>
        <h2>5. Limitation of Liability</h2>
        <p>
          In no event shall RateMyProfessor.space be liable for any indirect, incidental, special, consequential or
          punitive damages arising out of your use of the Service.
        </p>
        <h2>6. Changes to Terms</h2>
        <p>
          We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will
          provide notice of any changes by posting the new Terms of Service on this page.
        </p>
        <h2>7. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us through our website.</p>
      </div>
    </div>
  )
} 